CXXFLAGS=-std=c++14

taska: social.cpp 
	g++ $(CXXFLAGS) -o taska social.cpp 

taskb: social2.cpp 
	g++ $(CXXFLAGS) -o taskb social2.cpp 

taskc: social3.cpp 
	g++ $(CXXFLAGS) -o taskc social3.cpp 

clean:
		rm -f taska taskb taskc 